name: Build Aksharshala

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build tools and Qt6 dependencies
      run: |
       sudo apt update
       sudo apt install -y \
       build-essential \
       cmake \
       ninja-build \
       qt6-base-dev \
       qt6-webengine-dev \
       qt6-websockets-dev \
       qt6-tools-dev \
       qt6-base-dev-tools


    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -G Ninja

    - name: Build project
      run: |
        cd build
        ninja
